spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaanx4vraMGNBIUQ4x6
            client-secret: ixQq-_qlRPoev9ACAP2ITJJh5rkrvyu9kkQXwpe5
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-943830.okta.com/oauth2/default